version: '3.8'

# Services
services:

    # PHP Service
    php:
        build:
            dockerfile: php/Dockerfile
        ports: 
            - 5173:5173
            - 9000:9000
        volumes:
            - './www-data/codeigniter:/var/www/html'
        depends_on:
            - mariadb

    # Nginx Service
    nginx:
        image: nginx:latest
        ports:
            - 80:80
            - 81:81
        links:
            - 'php'
        volumes:
            - './www-data/codeigniter:/var/www/html'
            - './nginx:/etc/nginx/conf.d'
        depends_on:
            - php

    # MariaDB Service
    mariadb:
        image: mariadb:10.9
        environment:
            MYSQL_ROOT_PASSWORD: your_password
        volumes:
            - mysqldata:/var/lib/mysql

    # phpMyAdmin Service
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8080:80
        environment:
            PMA_HOST: mariadb
        depends_on:
            - mariadb

# Volumes
volumes:
  mysqldata: